=== theeryanwold/WRIT-5662-Structured-Authoring/Structured_Authoring-master/Structured.dtd
<!ELEMENT Offerings (Workshop+)>
<!ELEMENT Workshop (Topic, Presenters, Description, ID, Medium, Capacity, Length)>
<!ATTLIST Workshop Topic (Audience Analysis|Knowing the Context|Better Writing Better Meetings|Overcoming Technical Difficulties) #REQUIRED>
<!ELEMENT Presenters (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Medium (#PCDATA)>
<!ELEMENT Capacity (#PCDATA)>
<!ELEMENT Length (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Room (#PCDATA)>

=== theeryanwold/WRIT-5662-Structured-Authoring/Structured_Authoring-master/Structured_Language.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Offerings SYSTEM "Structured.dtd">

<Offerings>


  <Workshop Topic="Audience Analysis">
    <Topic>Audience Analysis</Topic>
    <Presenters>Ryan Wold and Brigitte Mussack</Presenters>
    <Description>Understanding whom you’re writing to and how you fit in their life.</Description>
    <ID>01</ID>
    <Medium>In Person</Medium>
    <Capacity>10-25 Students</Capacity>
    <Length>60-90 Minutes</Length>
  </Workshop>

  <Workshop Topic="Knowing the Context">
    <Topic>Knowing the Context</Topic>
    <Presenters>Daniel Card and Jeremy Rosselot-Merritt</Presenters>
    <Description>Determining the appropriate writing strategy for even the most challenging circumstances.</Description>
    <ID>02</ID>
    <Medium>In Person or Online</Medium>
    <Capacity>10-25 Students</Capacity>
    <Length>60-90 Minutes</Length>
  </Workshop>

  <Workshop Topic="Better Writing Better Meetings">
    <Topic>Better Writing Better Meeetings</Topic>
    <Presenters>Ryan Wold and Dan Card</Presenters>
    <Description>Developing best practices for communicating before, during, and after meetings to improve morale and maximize productivity.</Description>
    <ID>03</ID>
    <Medium>In Person and Online</Medium>
    <Capacity>10-25 Students</Capacity>
    <Length>45-60 Minutes</Length>
  </Workshop>

  <Workshop Topic="Overcoming Techincal Difficulties">
    <Topic>Audience Analysis</Topic>
    <Presenters>Jeremy Rosselot-Merritt and Brigitte Mussack</Presenters>
    <Description>Understanding whom you’re writing to and how you fit in their life.</Description>
    <ID>04</ID>
    <Medium>Online</Medium>
    <Capacity>10-40 Students</Capacity>
    <Length>60-90 Minutes</Length>
  </Workshop>



</Offerings>
